name: caller-java-sonar-ci

on:
 workflow_dispatch:
  
jobs:
  caller-java-sonar-ci:
    uses: Shanridhu/github-reusable-07072023/.github/workflows/java-sonar-reusable-ci.yml@main
    
    secrets:
         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
         SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
         SONARQUBE_HOST: ${{ secrets.SONARQUBE_HOST }}
   
