name: caller workflow

on:
 workflow_dispatch:
   inputs: 
     filename: 
        description: 'javaci'
        required: true
    
     filename2: 
        description: 'databaseci'
        required: true

jobs:

    trigger_javaci: 
       uses: Shanridhu/github-actions-shared-workflow/.github/workflows/javaci.yml@main
       
       secrets:
         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}

    trigger_databaseci: 
       uses: Shanridhu/github-actions-shared-workflow/.github/workflows/databaseci.yml@main


       secrets:
         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
