name: Call a reusable workflow

on:
 workflow_dispatch:


jobs:

    trigger_javaci: 
       uses: Shanridhu/github-actions-shared-workflow/.github/workflows/javaci.yml@main

    trigger_databaseci: 
       uses: Shanridhu/github-actions-shared-workflow/.github/workflows/databaseci.yml@main


defaults:
      run: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
