name: Call a reusable workflow

on:
 workflow_dispatch:

jobs:
  call-workflow:
    uses: Shanridhu/github-actions-shared-workflow/.github/workflows/javaci.yml@main
    #uses: Shanridhu/github-actions-shared-workflow/.github/workflows/databaseci.yml@main

    
    secrets:
      Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
