name: Call a reusable workflow

on:
 workflow_dispatch:
   inputs: 
     workflows: 
        description: 'please give any one file name to trigger javaci or databaseci'
        required: true
        #default: 'javaci,databaseci'
     #repository: 
      #  description: 'Repository to run workflows in'
       # required: true  
  
jobs:

    trigger_javaci: 
       
       uses: Shanridhu/github-actions-shared-workflow/.github/workflows/javaci.yml@main
       if: ${{github.event.input.workflows == 'javaci'}}
       secrets:
         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}

    trigger_databaseci: 
       
       uses: Shanridhu/github-actions-shared-workflow/.github/workflows/databaseci.yml@main
       if: ${{github.event.input.workflows == 'databaseci'}}
       secrets:
         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}




