name: caller workflow

on:
 workflow_dispatch:
   inputs: 
     filename:
        description: 'please give any one file name to trigger'
        type: string
        required: true



jobs:

    trigger_javaci: 
       uses: Shanridhu/github-actions-shared-workflow/.github/workflows/javaci.yml@main
       with:
        filename: "javaci"
       
       secrets:
         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}

    trigger_databaseci: 
       uses: Shanridhu/github-actions-shared-workflow/.github/workflows/databaseci.yml@main
       with:
        filename: "databaseci"

       secrets:
         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
