name: caller workflow

on:
  workflow_dispatch:
    inputs: [workflow1.yml, workflow2.yml]
    types:
      - completed

jobs:
   
   call-workflow:
    runs-on: ubuntu-latest
    
    steps:
     - name: trigger javaci 
       uses: Shanridhu/github-actions-shared-workflow/.github/workflows/javaci.yml@main
       with: 
         workflow_file: javaci.yml
           
         
     - name: trigger databaseci 
       uses: Shanridhu/github-actions-shared-workflow/.github/workflows/databaseci.yml@main
       with: 
        workflow_file: databaseci.yml
         
#      secrets:
 #         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
