name: Call a reusable workflow

on:
 workflow_dispatch:
   inputs: 
     workflows: 
        type: boolean
        description: 'please give any one file name to trigger javaci or databaseci'
        required: true
 
jobs:

    trigger_javaci: 
       if: ${{github.event.inputs.workflows == 'javaci'}}
       uses: Shanridhu/github-actions-shared-workflow/.github/workflows/javaci.yml@main
       
       secrets:
         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}

    trigger_databaseci: 
       if: ${{github.event.inputs.workflows == 'databaseci'}}
       uses: Shanridhu/github-actions-shared-workflow/.github/workflows/databaseci.yml@main
       
       secrets:
         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}




