name: caller workflow

on:
 workflow_dispatch:
   inputs: 
     filename: 
        description: 'please give any one file name to trigger'
       # value: $
        required: true

     # filename2: 
        # description: 'databaseci'
        # required: true

jobs:

    trigger_javaci: 
       uses: Shanridhu/github-actions-shared-workflow/.github/workflows/javaci.yml@main
       with:
        filename: ${{inputs.javaci.yml}}
       
       secrets:
         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}

    trigger_databaseci: 
       uses: Shanridhu/github-actions-shared-workflow/.github/workflows/databaseci.yml@main
       with:
        filename: ${{inputs.databaseci.yml}}

       secrets:
         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
