# This is a basic workflow to help you get started with Actions

name: Workflow2

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["workflow1"]
env:
  JAVA_VERSION: '11'
  
  
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
       baselineTag: ${{ github.event.client_payload.baselinetag }}
       revision_number: ${{ github.event.client_payload.revision_number }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
        
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                

      - name: Build project with Maven
        run: mvn -B package --file pom.xml
      

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo $baselineTag
          echo $revision_number
