name: Call a reusable workflow

on:
 workflow_dispatch:

jobs:
  call-workflow:
    uses: Shanridhu/github-actions-shared-workflow/.github/workflows/workflow1.yml@main

  #call-workflow-passing-data:
   # permissions:
    #  contents: read
     # pull-requests: write
    #uses: Shanridhu/github-actions-shared-workflow/.github/workflows/workflow1.yml@main
    with:
     JAVA_VERSION: '11'
    
    secrets:
      Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
